language: java
jdk:
  - oraclejdk8

# actual code is inside lacuna/lacuna
before_install: cd lacuna

# verify runs both unit and integration tests
script: mvn clean && mvn verify -B

after_success:
  - mvn jacoco:report coveralls:report

# OracleJDK 8 and JavaFX projects may need to update to the latest available version from a repository.
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - $HOME/.m2